format = """
[░▒▓](#baa3d2)\
[  ](bg:#baa3d2 fg:#0b0a0d)\
[](bg:#b075f0 fg:#baa3d2)\
$directory\
[](fg:#b075f0 bg:#4c3960)\
$git_branch\
$git_status\
[](fg:#4c3960 bg:#2b2136)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2b2136 bg:#261d30)\
$time\
[ ](fg:#261d30)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#b075f0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#4c3960"
format = '[[ $symbol $branch ](fg:#b075f0 bg:#4c3960)]($style)'

[git_status]
style = "bg:#4c3960"
format = '[[($all_status$ahead_behind )](fg:#b075f0 bg:#4c3960)]($style)'

[nodejs]
symbol = ""
style = "bg:#2b2136"
format = '[[ $symbol ($version) ](fg:#b075f0 bg:#2b2136)]($style)'

[rust]
symbol = ""
style = "bg:#2b2136"
format = '[[ $symbol ($version) ](fg:#b075f0 bg:#2b2136)]($style)'

[golang]
symbol = ""
style = "bg:#2b2136"
format = '[[ $symbol ($version) ](fg:#b075f0 bg:#2b2136)]($style)'

[php]
symbol = ""
style = "bg:#2b2136"
format = '[[ $symbol ($version) ](fg:#b075f0 bg:#2b2136)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#261d30"
format = '[[  $time ](fg:#b4a0ca bg:#261d30)]($style)'
